### PR TITLE
New Swap

### PR DESCRIPTION
**Pull request by florianv**
I decided to move core features to an independent library (https://github.com/florianv/exchanger) and Swap is now acting as an "easy" wrapper around Exchanger.

Fixes https://github.com/florianv/swap/issues/51 https://github.com/florianv/swap/issues/21 https://github.com/florianv/swap/issues/19

### CODE REVIEW

**Comment by Nyholm** [comment]
I've looked at the changes in this repo and Im 👍 

I've just given a quick glimpse on the exchanger repo. It looks good. I have not made a careful review yet though.

Im +1 for merging this and make a 0.1.0 tag on the exchanger.

**Comment by florianv** [comment]
Thanks for your feedback @Nyholm !

My goal was to have a good foundation (`Exchanger`) while keeping the simplicity of `Swap`, which is why it's popular today. Now Swap does not implement any interface so we are free to add more methods in case we support new exchange queries in the future, so it's more flexible.

I will leave this open a few more days for inputs. I still have to improve the documentation and I hope to do be able to do it this weekend.

> Im +1 for merging this and make a 0.1.0 tag on the exchanger.

Yes I agree. Once it's merged, I will leave it in beta for inputs during one week or two before tagging everything and updating the Symfony bundle and Laravel package.

@sagikazarmark I see `moneyphp/money` is still in beta, so maybe it wants to rely on Swap 3.0 instead of 2.0. I can send a PR once we are done here.

**Comment by sagikazarmark** [comment]
> I can send a PR once we are done here.

That would be really cool, thanks.

**Comment by florianv** [comment]
I'm merging this and leave it open for inputs on the master branch

**Comment by sagikazarmark** [comment]
I am wondering about the with* methods: looking at the implementation it's not immutable which might be confusing in this hypie world.

I am also wondering whether Money should rely on swap or exchanger. WDYT?

**Comment by florianv** [comment]
> I am wondering about the with* methods: looking at the implementation it's not immutable which might be confusing in this hypie world.

Yes, it can be misleading. I will send a PR to change that.

> I am also wondering whether Money should rely on Swap or Exchanger. WDYT?

`Swap` is a wrapper around `Exchanger`, so I think it could rely on both. Accept either a `Swap` instance or an `Exchanger` instance and wrap it with `Swap`. Use `Swap` internally

**Pull request merged**
