### PR TITLE
Update swap towards latest exchanger version.

### PR DESCRIPTION
**Pull request by ddinchev**
Improved the readme. Bumped the exchanger dependency version.

### CODE REVIEW

**Comment by florianv** [comment]
Thanks for you PR @ddinchev :)

Would be fantastic if you could update the Fixer usages in the documentation too 
https://github.com/florianv/swap/blob/master/doc/readme.md

Exchanger `1.1.0` was just released so it should work straight once the build runs again!

**Comment by przemekperon** [comment]
Also waiting for this PR to be merged.

**Comment by florianv** [comment]
@ddinchev Can you please update this PR to use exchanger `1.1` ?

**Comment by ddinchev** [comment]
@florianv it already is updated but `exchanger:1.1` wasn't released yet. I can push a dummy change to trigger the rebuild if you can't do that manually?

**Comment by florianv** [comment]
@ddinchev I restarted the build but the tests are failing!

**Comment by ddinchev** [comment]
@florianv all green now ;)

**Comment by florianv** [comment]
Thanks @ddinchev

**Pull request merged**
