### PR TITLE
Use add() instead of with()

### PR DESCRIPTION
**Pull request by florianv**
Use `add()` instead of `with()` in the Builder.

### CODE REVIEW

**Comment by florianv** [comment]
Thanks @sagikazarmark for raising this issue

**Comment by Nyholm** [comment]
👍

**Comment by sagikazarmark** [comment]
Much better, although add is still a little bit confusing for me: it's
rather used for adding a value to a collection. But it's okay. Looks like
you are trying to avoid set on purpose.

**Comment by florianv** [comment]
> Much better, although add is still a little bit confusing for me: it's
rather used for adding a value to a collection.

Actually this is the case, you can call `add` multiple times to add multiple services to the chain

**Comment by sagikazarmark** [comment]
Ah, sorry, haven't actually reviewed all the changes. I rather meant cache and http client, but use is cool.

**Pull request merged**
